In [2]:
import pandas as pd 
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score
from sklearn.compose import ColumnTransformer

In [3]:
df = pd.read_csv('./train (1).csv')[['Age','Fare','SibSp','Parch','Survived']]
df

      Age     Fare  SibSp  Parch  Survived
0    22.0   7.2500      1      0         0
1    38.0  71.2833      1      0         1
2    26.0   7.9250      0      0         1
3    35.0  53.1000      1      0         1
4    35.0   8.0500      0      0         0
..    ...      ...    ...    ...       ...
886  27.0  13.0000      0      0         0
887  19.0  30.0000      0      0         1
888   NaN  23.4500      1      2         0
889  26.0  30.0000      0      0         1
890  32.0   7.7500      0      0         0

[891 rows x 5 columns]

In [4]:
df.dropna(inplace=True)

In [5]:
df.head()

    Age     Fare  SibSp  Parch  Survived
0  22.0   7.2500      1      0         0
1  38.0  71.2833      1      0         1
2  26.0   7.9250      0      0         1
3  35.0  53.1000      1      0         1
4  35.0   8.0500      0      0         0

In [6]:
df['family'] = df['SibSp'] + df['Parch']

In [7]:
df.head()

    Age     Fare  SibSp  Parch  Survived  family
0  22.0   7.2500      1      0         0       1
1  38.0  71.2833      1      0         1       1
2  26.0   7.9250      0      0         1       0
3  35.0  53.1000      1      0         1       1
4  35.0   8.0500      0      0         0       0

In [8]:
df.drop(columns=['SibSp' , 'Parch'],inplace=True)

In [9]:
df.head()

    Age     Fare  Survived  family
0  22.0   7.2500         0       1
1  38.0  71.2833         1       1
2  26.0   7.9250         1       0
3  35.0  53.1000         1       1
4  35.0   8.0500         0       0

In [10]:
X = df.drop(columns=['Survived'])
y = df['Survived']

In [11]:
X_train,X_test,Y_train,Y_test = train_test_split(X,y,test_size=20,random_state=42)

In [12]:
X_train.head()

      Age      Fare  family
71   16.0   46.9000       7
259  50.0   26.0000       1
852   9.0   15.2458       2
737  35.0  512.3292       0
225  22.0    9.3500       0

In [15]:
# Without binarization

clf = DecisionTreeClassifier()
clf.fit(X_train,Y_train)
y_pred = clf.predict(X_test)
accuracy_score(Y_test,y_pred)

0.7