#Importing Pandas

In [2]:
import pandas as pd

# Opening a local CSV

In [8]:
df = pd.read_csv('/content/sample_dataset_250.csv')
df

,enrollee_id,city,city_development_index,gender,relevant_experience,enrolled_university,education_level,major_discipline,experience,company_size
0,7396,city_103,0.821,Male,Has relevant experience,Full time course,Graduate,No Major,2,5000-9999
1,2182,city_103,0.497,Male,Has relevant experience,Full time course,High School,Business Degree,14,500-999
2,525,city_71,0.853,NaN,No relevant experience,Part time course,Phd,Business Degree,6,1000-4999
3,6798,city_40,0.640,Female,No relevant experience,Part time course,Graduate,Arts,17,10-49
4,24907,city_40,0.726,NaN,No relevant experience,Full time course,Graduate,STEM,>20,100-500
...,...,...,...,...,...,...,...,...,...,...
245,15784,city_98,0.611,Female,No relevant experience,NaN,Phd,Humanities,8,1000-4999
246,33707,city_33,0.699,Male,No relevant experience,Part time course,Masters,Humanities,10,5000-9999
247,3096,city_55,0.882,NaN,Has relevant experience,no_enrollment,Phd,No Major,18,5000-9999
248,19445,city_21,0.548,Male,No relevant experience,Full time course,High School,No Major,20,1000-4999
249,16964,city_71,0.861,NaN,No relevant experience,NaN,Masters,Humanities,5,50-99

# Opening a csv file from an URL

In [4]:
import requests
from io import StringIO

In [6]:
# url= "https://github.com/umpirsky/country-list/blob/master/data/en_US/country.csv"
# headers = {"User-Agent" : "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.14; rv:66.0) Gecko/20100101 Firefox/66.0"}
# req = requests.get(url , headers=headers)
# data = StringIO(req.text)

# pd.read_csv(data)

In [7]:
import pandas as pd
import requests
from io import StringIO

url = "https://raw.githubusercontent.com/umpirsky/country-list/master/data/en_US/country.csv"

headers = {
    "User-Agent": "Mozilla/5.0"
}

req = requests.get(url, headers=headers)

data = StringIO(req.text)

df = pd.read_csv(data)

print(df.head())

   id           value
0  AF     Afghanistan
1  AX   Åland Islands
2  AL         Albania
3  DZ         Algeria
4  AS  American Samoa

#Sep Parameter

### In below first parameter is the dataset location and second parameter is the seprated value like comma , tab. this second parameter overwrite the default comma and last is the a Array of names that accepts the column names for the dataset

In [ ]:
pd.read_csv('dataLocation' , sep='' , name=[])

# Index_col parameter

### if you want to replace any of the column in data set so you can use below of the code

In [ ]:
pd.read_csv('datasetLocation' , index_col = 'columnName')

# 6.Header Parameter

### if you want to delete first row to the dataset so you can use it

In [ ]:
pd.read_csv('test.csv' , header = 1)

# 7. use_cols parameter

### **if you want to delete some column from the dataset or if you want only specific column in the training dataset so you can use this line of code**

in usecols pass all the column name that you want to use in the dataset

In [ ]:
pd.read_csv('test.csv' , usecols=[''])

# 8.Squeeze parameter

### in this if you want only one column in the data set so you can use. this one make the dataset like a pandas series

In [ ]:
from numpy import squeeze
pd.read_csv('test.csv' , usecols=['gender'] , squeeze=True)

# 9. Skiprows/nrows Parameter

### If you want to delete some entries in the dataset so you can use this function skiprows

### if you want to use some entries like only 100 entries so you can use nrows and pass the number that much entries you want show in the dataset

In [10]:
pd.read_csv('/content/sample_dataset_250.csv' , skiprows=[0,1])

,2182,city_103,0.497,Male,Has relevant experience,Full time course,High School,Business Degree,14,500-999
0,525,city_71,0.853,NaN,No relevant experience,Part time course,Phd,Business Degree,6,1000-4999
1,6798,city_40,0.640,Female,No relevant experience,Part time course,Graduate,Arts,17,10-49
2,24907,city_40,0.726,NaN,No relevant experience,Full time course,Graduate,STEM,>20,100-500
3,19065,city_40,0.878,Male,No relevant experience,Part time course,High School,Humanities,5,1000-4999
4,23383,city_115,0.785,NaN,Has relevant experience,Full time course,Masters,Business Degree,14,5000-9999
...,...,...,...,...,...,...,...,...,...,...
243,15784,city_98,0.611,Female,No relevant experience,NaN,Phd,Humanities,8,1000-4999
244,33707,city_33,0.699,Male,No relevant experience,Part time course,Masters,Humanities,10,5000-9999
245,3096,city_55,0.882,NaN,Has relevant experience,no_enrollment,Phd,No Major,18,5000-9999
246,19445,city_21,0.548,Male,No relevant experience,Full time course,High School,No Major,20,1000-4999
247,16964,city_71,0.861,NaN,No relevant experience,NaN,Masters,Humanities,5,50-99

# 10. Encoding Parameter

### There is a one type of error occurd in the first time load the data is UnicodeDecodeError

### that means the encoding of data is different so go to any type of code Editor and change the encoding formate of the data then you can use the data for training purpose

In [12]:
 pd.read_csv('/content/sample_dataset_250.csv')

,enrollee_id,city,city_development_index,gender,relevant_experience,enrolled_university,education_level,major_discipline,experience,company_size
0,7396,city_103,0.821,Male,Has relevant experience,Full time course,Graduate,No Major,2,5000-9999
1,2182,city_103,0.497,Male,Has relevant experience,Full time course,High School,Business Degree,14,500-999
2,525,city_71,0.853,NaN,No relevant experience,Part time course,Phd,Business Degree,6,1000-4999
3,6798,city_40,0.640,Female,No relevant experience,Part time course,Graduate,Arts,17,10-49
4,24907,city_40,0.726,NaN,No relevant experience,Full time course,Graduate,STEM,>20,100-500
...,...,...,...,...,...,...,...,...,...,...
245,15784,city_98,0.611,Female,No relevant experience,NaN,Phd,Humanities,8,1000-4999
246,33707,city_33,0.699,Male,No relevant experience,Part time course,Masters,Humanities,10,5000-9999
247,3096,city_55,0.882,NaN,Has relevant experience,no_enrollment,Phd,No Major,18,5000-9999
248,19445,city_21,0.548,Male,No relevant experience,Full time course,High School,No Major,20,1000-4999
249,16964,city_71,0.861,NaN,No relevant experience,NaN,Masters,Humanities,5,50-99

# 11. Skip bad lines

### if the data is not in the csv but not complete data but some of the rows are not in stadard so you can skip that rows

In [ ]:
pd.read_csv('/content/sample_dataset_250.csv' , sep=';' , encoding='latin-1' , error_bad_lines=False)

#12.dtypes parameter

In [13]:
pd.read_csv('/content/sample_dataset_250.csv' , ).info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 250 entries, 0 to 249
Data columns (total 10 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   enrollee_id             250 non-null    int64
 1   city                    250 non-null    object
 2   city_development_index  250 non-null    float64
 3   gender                  149 non-null    object
 4   relevant_experience     250 non-null    object
 5   enrolled_university     177 non-null    object
 6   education_level         250 non-null    object
 7   major_discipline        250 non-null    object
 8   experience              250 non-null    object
 9   company_size            223 non-null    object
dtypes: float64(1), int64(1), object(8)
memory usage: 19.7+ KB

In [14]:
pd.read_csv('/content/sample_dataset_250.csv' , dtype={'target' : int}).info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 250 entries, 0 to 249
Data columns (total 10 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   enrollee_id             250 non-null    int64
 1   city                    250 non-null    object
 2   city_development_index  250 non-null    float64
 3   gender                  149 non-null    object
 4   relevant_experience     250 non-null    object
 5   enrolled_university     177 non-null    object
 6   education_level         250 non-null    object
 7   major_discipline        250 non-null    object
 8   experience              250 non-null    object
 9   company_size            223 non-null    object
dtypes: float64(1), int64(1), object(8)
memory usage: 19.7+ KB

#13. Hnadling Dates

### if the normal dataset the look like object so we want to use filter on the date so change the type of the date in dateTime type

In [ ]:
pd.read_csv('/content/sample_dataset_250.csv' , parse_dates=['date'] ).info()

#14 Convertors

In [15]:
def rename(name):
  if (name == "Royal Challengers Bangalore"):
      return "RCB"
  else:
      return name

In [16]:
rename("Royal Challengers Bangalore")

'RCB'

In [ ]:
pd.read_csv('/content/sample_dataset_250.csv' , converters={'team1' : rename} )

#15 na_values parameters

In [17]:
pd.read_csv('/content/sample_dataset_250.csv' , na_values=['Male'])

,enrollee_id,city,city_development_index,gender,relevant_experience,enrolled_university,education_level,major_discipline,experience,company_size
0,7396,city_103,0.821,NaN,Has relevant experience,Full time course,Graduate,No Major,2,5000-9999
1,2182,city_103,0.497,NaN,Has relevant experience,Full time course,High School,Business Degree,14,500-999
2,525,city_71,0.853,NaN,No relevant experience,Part time course,Phd,Business Degree,6,1000-4999
3,6798,city_40,0.640,Female,No relevant experience,Part time course,Graduate,Arts,17,10-49
4,24907,city_40,0.726,NaN,No relevant experience,Full time course,Graduate,STEM,>20,100-500
...,...,...,...,...,...,...,...,...,...,...
245,15784,city_98,0.611,Female,No relevant experience,NaN,Phd,Humanities,8,1000-4999
246,33707,city_33,0.699,NaN,No relevant experience,Part time course,Masters,Humanities,10,5000-9999
247,3096,city_55,0.882,NaN,Has relevant experience,no_enrollment,Phd,No Major,18,5000-9999
248,19445,city_21,0.548,NaN,No relevant experience,Full time course,High School,No Major,20,1000-4999
249,16964,city_71,0.861,NaN,No relevant experience,NaN,Masters,Humanities,5,50-99

#16 Loading a huge dateset in chunks

In [19]:
dfs = pd.read_csv('/content/sample_dataset_250.csv' ,chunksize=50)

In [20]:
for chunks in dfs :
    print(chunks.shape)

(50, 10)
(50, 10)
(50, 10)
(50, 10)
(50, 10)